### PR TITLE
new homepage

### PR DESCRIPTION
**Pull request by nylira**
New homepage design based on @jolesbi's mockups. Not ready for merge yet, still have some issues:

* no working links in the footer yet
* lacking some imagery for "Scalability" and "Developer Friendly"
* lacking links to the "Why Use Cosmos" section. @jolesbi where do you think these links should go?
* lacking spacing for desktop designs
* lacking Kevin's new backdrop

fireshot capture 20 - cosmos - internet of blockchains - http___localhost_8700_

### CODE REVIEW

**Comment by jolesbi** [comment]
this is so great! i'll work on improving assets.

**Comment by nylira** [comment]
Updates today:

* fixed all of the links
* added Kevin's backdrop and redid the cover layout for a more readable logo, text, and action button
* added a button to let users know they can scroll down
* some of the "Why Use Cosmos?" links use a scroll/easing library to get to specific parts of the /intro page
* improved layout of the homepage
* app header uses the cosmos atom instead of showing cosmos text (reduce redundancy)
* updated variables to latest from cosmos-ui, fixing some visibility issues
* removed IRC and Facebook from Community links

Things left to do @jolesbi 
* assets for "Scalability" and "Developer Friendly"
* improve "Validator" and "Atoms" assets (low priority)

When that's done I think we can deploy it!

fireshot capture 21 - cosmos - internet of blockchains - http___localhost_8700_

**Comment by faboweb** [comment]
That looks pretty nice :)

**Comment by jolesbi** [comment]
@nylira are we using the same colors from the ui variables file?

**Comment by nylira** [comment]
@jolesbi yep!

**Comment by gamarin2** [comment]
Awesome! Looks so very nice :)

Not sure about the subtitle though "The interoperable, scalable, proof-of-stake blockchain network, built for developers". Here is why:

- I think overlapping with underlying planets looks weird
- Spacing between two parts of the sentence is too wide imo
- If we must keep it, I would remove 'proof-of-stake' from the sentence. "The interoperable, scalable blockchain network. Built for developers."

**Comment by gamarin2** [comment]
Also, is it the final copy? It still displays "Interoperability, Scalability, Developer Friendly", instead of "Interoperable, Scalable, Developer Friendly"

**Comment by jolesbi** [comment]
@nylira this PR still has the DO NOT MERGE label... but i think we're ready to go!

**Pull request merged**
